[package]
name = "plugin-demo"
version = "0.1.0"
authors = ["nejat <nejatoz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plugin-model = { path = "../plugin-model" }

[lib]
crate-type = ["dylib"]
